baseURL = "https://sabrinaadler.github.io/myblog/"
languageCode = "en-us"
title = "Sabrina's Blog"
theme = "PaperMod"
publishDir = "docs"
defaultContentLanguage = "en"
enableEmoji = true
relativeURLs = true
canonifyURLs = false

[params]
author = "Sabrina Adler"
description = "A blog on code, math, birds, and things in between."
math = true  # Enables LaTeX via KaTeX
showReadingTime = true

[params.assets]
  disableFingerprinting = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
  name = "Course Materials"
  url  = "/notes/"
  weight = 30



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# (Optional) to stop the warning in your console:
ignoreLogs = ["warning-goldmark-raw-html"]
